//
// Created by lodracir on 25/02/23.
//

#ifndef INC_001_MAKEFILE_TEST_MCU_H
#define INC_001_MAKEFILE_TEST_MCU_H

#if defined(STM32F3XX)
#include "stm32f3xx.h"
#endif

#define UNUSED(X) (void)X      /* To avoid gcc/g++ warnings */

/** STM32F303x8 GPIOx ALT FCN Defines **/
#if defined(STM32F303x8)

//AF0
#define GPIO_ALT_FCN_AF0_SYS_AF GPIO_ALT_FN_0

//AF1
#define GPIO_ALT_FCN_AF1_TIM2   GPIO_ALT_FN_1
#define GPIO_ALT_FCN_AF1_TIM15  GPIO_ALT_FN_1
#define GPIO_ALT_FCN_AF1_TIM16  GPIO_ALT_FN_1
#define GPIO_ALT_FCN_AF1_TIM17  GPIO_ALT_FN_1
#define GPIO_ALT_FCN_AF1_EVENT  GPIO_ALT_FN_1

//AF2
#define GPIO_ALT_FCN_AF2_TIM1   GPIO_ALT_FN_2
#define GPIO_ALT_FCN_AF2_TIM3   GPIO_ALT_FN_2
#define GPIO_ALT_FCN_AF2_TIM15  GPIO_ALT_FN_2
#define GPIO_ALT_FCN_AF2_TIM16  GPIO_ALT_FN_2

//AF3
#define GPIO_ALT_FCN_AF3_TSC    GPIO_ALT_FN_3

//AF4
#define GPIO_ALT_FCN_AF4_I2C1   GPIO_ALT_FN_4
#define GPIO_ALT_FCN_AF4_TIM1   GPIO_ALT_FN_4

//AF5
#define GPIO_ALT_FCN_AF5_SPI1   GPIO_ALT_FN_5
#define GPIO_ALT_FCN_AF5_INFRARED GPIO_ALT_FN_5

//AF6
#define GPIO_ALT_FCN_AF6_TIM1   GPIO_ALT_FN_6
#define GPIO_ALT_FCN_AF6_INFRARED GPIO_ALT_FN_6

//AF7
#define GPIO_ALT_FCN_AF7_USART1 GPIO_ALT_FN_7
#define GPIO_ALT_FCN_AF7_USART2 GPIO_ALT_FN_7
#define GPIO_ALT_FCN_AF7_USART3 GPIO_ALT_FN_7
#define GPIO_ALT_FCN_AF7_GPCOMP6 GPIO_ALT_FN_7

//AF8
#define GPIO_ALT_FCN_AF8_GPCOMP2 GPIO_ALT_FN_8
#define GPIO_ALT_FCN_AF8_GPCOMP4 GPIO_ALT_FN_8
#define GPIO_ALT_FCN_AF8_GPCOMP6 GPIO_ALT_FN_8

//AF9
#define GPIO_ALT_FCN_AF9_CAN    GPIO_ALT_FN_9
#define GPIO_ALT_FCN_AF9_TIM1   GPIO_ALT_FN_9
#define GPIO_ALT_FCN_AF9_TIM15  GPIO_ALT_FN_9

//AF10
#define GPIO_ALT_FCN_AF10_TIM2  GPIO_ALT_FN_10
#define GPIO_ALT_FCN_AF10_TIM3  GPIO_ALT_FN_10
#define GPIO_ALT_FCN_AF10_TIM17 GPIO_ALT_FN_10

//AF11
#define GPIO_ALT_FCN_AF11_TIM1  GPIO_ALT_FN_11

//AF12
#define GPIO_ALT_FCN_AF12_TIM1  GPIO_ALT_FN_12

//AF13
#define GPIO_ALT_FCN_AF13_OPAMP2 GPIO_ALT_FN_13

//AF14

//AF15
#define GPIO_ALT_FCN_AF15_EVENT GPIO_ALT_FN_15

#elif defined(STM32F302xE)

#endif

#endif //INC_001_MAKEFILE_TEST_MCU_H
